name: Python Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ['3.10', '3.11', '3.12', '3.13']
        resolution: [lowest-direct, highest]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: pip install uv
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: pip
    - name: Install dependencies
      run: |
        uv sync --resolution=${{ matrix.resolution }}
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest . -k unit \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  integration:
    runs-on: gpu
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: pip install uv
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
    - name: Install dependencies
      run: |
        uv sync

    - uses: self-actuated/nvidia-run@master
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh
    - name: Start serving
      run: |
        ollama serve &
        sleep 5
        time curl -i http://localhost:11434

    - name: Pull llama2
      run: |
        ollama pull llama3.2:3b-instruct-fp16
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest . -k integration \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: pipx install uv
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: pip
    - run: |-
        uv sync
        uv run mypy .
