name: Python Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.11', '3.12']
        resolution: [lowest-direct, highest]
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: pip
    - name: Install dependencies
      run: |
        poetry config --local virtualenvs.create false
        poetry run pip install uv
        poetry run uv pip install --resolution=${{ matrix.resolution }} .
        poetry install --only dev
    - name: Run tests
      id: run-tests
      run: >
        poetry run pytest \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src tests \
          --log-level=DEBUG \
          --verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: poetry
    - run: |-
        poetry install
        poetry run mypy .
